#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab2.Views.Users
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using lab2;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Users/AboutMe.cshtml")]
    public partial class AboutMe : System.Web.Mvc.WebViewPage<lab2.ViewModels.UsersViewModel>
    {
        public AboutMe()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Users\AboutMe.cshtml"
  
	ViewBag.Title = "Create";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>Create</h2>\r\n\r\n\r\n");

            
            #line 10 "..\..\Views\Users\AboutMe.cshtml"
 using (Html.BeginForm())
{
	
            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\Users\AboutMe.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\Users\AboutMe.cshtml"
                            


            
            #line default
            #line hidden
WriteLiteral("\t<div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n\t\t<h4>User</h4>\r\n\t\t<hr />\r\n");

WriteLiteral("\t\t");

            
            #line 17 "..\..\Views\Users\AboutMe.cshtml"
   Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\t\t<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t");

            
            #line 20 "..\..\Views\Users\AboutMe.cshtml"
       Write(Html.LabelFor(model => model.UserName, new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t<div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 22 "..\..\Views\Users\AboutMe.cshtml"
           Write(Html.ValueFor(model => model.UserName));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 23 "..\..\Views\Users\AboutMe.cshtml"
           Write(Html.ValidationMessageFor(model => model.UserName));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t</div>\r\n\t\t</div>\r\n\r\n\t\t<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t");

            
            #line 28 "..\..\Views\Users\AboutMe.cshtml"
       Write(Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t<div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 30 "..\..\Views\Users\AboutMe.cshtml"
           Write(Html.ValueFor(model => model.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 31 "..\..\Views\Users\AboutMe.cshtml"
           Write(Html.ValidationMessageFor(model => model.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t</div>\r\n\t\t</div>\r\n\r\n\t</div>\r\n");

            
            #line 36 "..\..\Views\Users\AboutMe.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("\t");

            
            #line 39 "..\..\Views\Users\AboutMe.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
