#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab2.Views.Users
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using lab2;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Users/UsersWithTicketsList.cshtml")]
    public partial class UsersWithTicketsList : System.Web.Mvc.WebViewPage<Dictionary<string,string>>
    {
        public UsersWithTicketsList()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Users\UsersWithTicketsList.cshtml"
  
	ViewBag.Title = "Userslist";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n");

WriteLiteral("\t");

            
            #line 8 "..\..\Views\Users\UsersWithTicketsList.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\t<div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n\t\t<hr />\r\n\t\t<table>\r\n");

            
            #line 13 "..\..\Views\Users\UsersWithTicketsList.cshtml"
			
            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\Users\UsersWithTicketsList.cshtml"
              

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t<tr>\r\n\t\t\t\t\t<td>\r\n\t\t\t\t\t\tUserName\r\n\t\t\t\t\t</td>\r\n\t\t\t\t\t<td>\r\n\t\t\t\t\t\tArtistName\r\n\t\t\t" +
"\t\t</td>\r\n\t\t\t\t</tr>\r\n");

            
            #line 22 "..\..\Views\Users\UsersWithTicketsList.cshtml"
				foreach (var str in Model)
				{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t<tr>\r\n\t\t\t\t\t\t<td>");

            
            #line 25 "..\..\Views\Users\UsersWithTicketsList.cshtml"
                       Write(str.Key);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n\t\t\t\t\t\t<td>");

            
            #line 26 "..\..\Views\Users\UsersWithTicketsList.cshtml"
                       Write(str.Value);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n\t\t\t\t\t</tr>\r\n");

            
            #line 28 "..\..\Views\Users\UsersWithTicketsList.cshtml"
				}
			
            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t</table>\r\n\r\n\t</div>\r\n\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("\t");

            
            #line 35 "..\..\Views\Users\UsersWithTicketsList.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
