#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab2.Views.Users
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using lab2;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Users/UsersList.cshtml")]
    public partial class UsersList : System.Web.Mvc.WebViewPage<List<string>>
    {
        public UsersList()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Users\UsersList.cshtml"
  
	ViewBag.Title = "Userslist";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n");

WriteLiteral("\t");

            
            #line 8 "..\..\Views\Users\UsersList.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\t<div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n\t\t<h4>UserName</h4>\r\n\t\t<hr />\r\n");

            
            #line 13 "..\..\Views\Users\UsersList.cshtml"
		
            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\Users\UsersList.cshtml"
          
			foreach (var str in Model)
			{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t<p>");

            
            #line 16 "..\..\Views\Users\UsersList.cshtml"
              Write(str);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 17 "..\..\Views\Users\UsersList.cshtml"
			}
		
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\t</div>\r\n\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("\t");

            
            #line 23 "..\..\Views\Users\UsersList.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
